---
- name: Install NTP 
  yum: name=ntp state=present disablerepo=* enablerepo=local
#- name: Instatll common dependencies(ansible module dependencies)
#  yum: name={{item}} state=present
#  with_items:
#    - libselinux-python
#    - libsemanage-python
- name: Configure ntp file
  template: src={{ansible_distribution_major_version}}/ntp.conf dest=/etc/ backup=yes
  notify: restart ntp
- name: Start ntp service
  service: name=ntpd state=started

- name: Stop iptables
  service: name=iptables state=stopped enabled=no
  when: ansible_distribution_major_version == '6'
