---
- name: Copy createrepo packages to remote host
  copy: src={{ansible_distribution_major_version}}/createrepo dest={{repo_path}} force=no

- name: Install createrepo
  yum: name={{repo_path}}/createrepo/{{item}} state=present 
  with_items:
    - libxml2-2.7.6-21.el6_8.1.x86_64.rpm
    - libxml2-python-2.7.6-21.el6_8.1.x86_64.rpm
    - deltarpm-3.5-0.5.20090913git.el6.x86_64.rpm
    - python-deltarpm-3.5-0.5.20090913git.el6.x86_64.rpm
    - createrepo-0.9.9-27.el6_9.noarch.rpm
  when: ansible_distribution_major_version == '6' 

- name: Install createrepo
  yum: name={{repo_path}}/createrepo/{{item}} state=present 
  with_items:
    - libxml2-2.9.1-6.el7_2.3.x86_64.rpm
    - libxml2-python-2.9.1-6.el7_2.3.x86_64.rpm
    - deltarpm-3.6-3.el7.x86_64.rpm
    - python-deltarpm-3.6-3.el7.x86_64.rpm 
    - createrepo-0.9.9-28.el7.noarch.rpm
  when: ansible_distribution_major_version == '7' 

- name: Copy packages to Zabbix SERVER hosts
  copy: src={{ansible_distribution_major_version}}/zabbix_server/ dest={{repo_path}} force=no
  notify: update repo data
  when: inventory_hostname in groups['server']
- name: Copy packages to Zabbix PROXY hosts
  copy: src={{ansible_distribution_major_version}}/zabbix_proxy/ dest={{repo_path}} force=no
  notify: update repo data
  when: inventory_hostname in groups['proxy']
- name: Copy packages to MySQL Server  hosts
  copy: src={{ansible_distribution_major_version}}/mysql dest={{repo_path}} force=no
  notify: update repo data
  when: inventory_hostname in groups['alldb']

- name: Add local repo file
  yum_repository: name=local description="local repo" baseurl=file://{{repo_path}} gpgcheck=no enabled=yes

- name: Create local repo database
  command: createrepo {{repo_path}}
  notify: yum clean all
