---
## Apply common configuration to all nodes,like local yum repo,pull packs and time synchronize
- name: Pre-tasks copy packs, create local repository, make time synchronized
  hosts: server
#  become_user: false
  remote_user: root
  roles:
    - common

- name: Install zabbix SERVER
  hosts: server
  remote_user: root
  roles:
    - server

